seed: 42

logger:
  save_dir: logs
  name: experiment1

data:
  data_path: data/BTCUSDT/
  src_length: 24
  tgt_length: 1
  seg_length: 60
  batch_size: 32
  val_split: 0.2
  test_split: 0.1
  num_workers: 4

model:
  input_dim: 4
  hidden_dim: 32
  output_dim: 32
  seg_length: 60
  lr: 0.002

trainer:
  max_epochs: 20
