seed: 42

trainer:
  max_epochs: 50

model:
  input_dim: 4
  hidden_dim: 32
  output_dim: 4
  lr: 0.002

data:
  csv_path: data/BTCUSDT.csv
  seq_length: 30      # length of input sequence
  batch_size: 64
  val_split: 0.2
  test_split: 0.1
  num_workers: 8
